---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nqbusxs1sf2w/public_html/app.wrabbitcapital.com/
    - /bin/cp -R core_invapp $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -rf content $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH